### ISSUE TITLE
Move to new organization?

### ISSUE THREAD

**Issue by dlfivefifty** [ehkropf/ComplexPhasePortrait.jl#3]
I was thinking that it might make sense to move this package to a new organization that we are both owners of. Something like "JuliaHolomorphic", "JuliaComplexAnalysis" or "JuliaAnalyticFunctions".  This could also host RiemannHilbert.jl and Holomorphic.jl (two packages currently in JuliaApproximation).

This would make it easier for me to help manage the package, for example, I could register ComplexPhasePortrait.jl and add Travis, etc.

Thoughts?

**Comment by ehkropf** [comment]
Hi Sheehan,

I'm cool with that. You pick where you'd like it to go, and I'll be glad to
work with you this evening or this weekend on moving it.

**Comment by dlfivefifty** [comment]
Sounds good!

I think I’ll go with JuliaHolomorphic, as there is no chance of confusion as there would be with JuliaComplexAnalysis or JuliaAnalyticFunctions. Also it’s shorter.

**Comment by ehkropf** [comment]
Done!
